// Mocks generated by Mockito 5.4.6 from annotations
// in invest_agent/test/trading_service_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:grpc/service_api.dart' as _i2;
import 'package:grpc/src/client/call.dart' as _i3;
import 'package:invest_agent/model/proto/generated/invest_agent.pb.dart' as _i6;
import 'package:invest_agent/model/proto/generated/invest_agent.pbgrpc.dart'
    as _i5;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i7;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeResponseStream_0<R> extends _i1.SmartFake
    implements _i2.ResponseStream<R> {
  _FakeResponseStream_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeClientCall_1<Q1, R1> extends _i1.SmartFake
    implements _i3.ClientCall<Q1, R1> {
  _FakeClientCall_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeResponseFuture_2<R1> extends _i1.SmartFake
    implements _i2.ResponseFuture<R1> {
  _FakeResponseFuture_2(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeFuture_3<T> extends _i1.SmartFake implements _i4.Future<T> {
  _FakeFuture_3(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeStreamSubscription_4<T> extends _i1.SmartFake
    implements _i4.StreamSubscription<T> {
  _FakeStreamSubscription_4(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [InvestAgentServiceClient].
///
/// See the documentation for Mockito's code generation for more information.
class MockInvestAgentServiceClient extends _i1.Mock
    implements _i5.InvestAgentServiceClient {
  MockInvestAgentServiceClient() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.ResponseStream<_i6.TradingResponse> calculateIndicators(
    _i4.Stream<_i6.TradingRequest>? request, {
    _i2.CallOptions? options,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #calculateIndicators,
              [request],
              {#options: options},
            ),
            returnValue: _FakeResponseStream_0<_i6.TradingResponse>(
              this,
              Invocation.method(
                #calculateIndicators,
                [request],
                {#options: options},
              ),
            ),
          )
          as _i2.ResponseStream<_i6.TradingResponse>);

  @override
  _i3.ClientCall<Q, R> $createCall<Q, R>(
    _i2.ClientMethod<Q, R>? method,
    _i4.Stream<Q>? requests, {
    _i2.CallOptions? options,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #$createCall,
              [method, requests],
              {#options: options},
            ),
            returnValue: _FakeClientCall_1<Q, R>(
              this,
              Invocation.method(
                #$createCall,
                [method, requests],
                {#options: options},
              ),
            ),
          )
          as _i3.ClientCall<Q, R>);

  @override
  _i2.ResponseFuture<R> $createUnaryCall<Q, R>(
    _i2.ClientMethod<Q, R>? method,
    Q? request, {
    _i2.CallOptions? options,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #$createUnaryCall,
              [method, request],
              {#options: options},
            ),
            returnValue: _FakeResponseFuture_2<R>(
              this,
              Invocation.method(
                #$createUnaryCall,
                [method, request],
                {#options: options},
              ),
            ),
          )
          as _i2.ResponseFuture<R>);

  @override
  _i2.ResponseStream<R> $createStreamingCall<Q, R>(
    _i2.ClientMethod<Q, R>? method,
    _i4.Stream<Q>? requests, {
    _i2.CallOptions? options,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #$createStreamingCall,
              [method, requests],
              {#options: options},
            ),
            returnValue: _FakeResponseStream_0<R>(
              this,
              Invocation.method(
                #$createStreamingCall,
                [method, requests],
                {#options: options},
              ),
            ),
          )
          as _i2.ResponseStream<R>);
}

/// A class which mocks [ResponseStream].
///
/// See the documentation for Mockito's code generation for more information.
class MockResponseStream<R> extends _i1.Mock implements _i2.ResponseStream<R> {
  MockResponseStream() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.ResponseFuture<R> get single =>
      (super.noSuchMethod(
            Invocation.getter(#single),
            returnValue: _FakeResponseFuture_2<R>(
              this,
              Invocation.getter(#single),
            ),
          )
          as _i2.ResponseFuture<R>);

  @override
  _i4.Future<Map<String, String>> get headers =>
      (super.noSuchMethod(
            Invocation.getter(#headers),
            returnValue: _i4.Future<Map<String, String>>.value(
              <String, String>{},
            ),
          )
          as _i4.Future<Map<String, String>>);

  @override
  _i4.Future<Map<String, String>> get trailers =>
      (super.noSuchMethod(
            Invocation.getter(#trailers),
            returnValue: _i4.Future<Map<String, String>>.value(
              <String, String>{},
            ),
          )
          as _i4.Future<Map<String, String>>);

  @override
  bool get isBroadcast =>
      (super.noSuchMethod(Invocation.getter(#isBroadcast), returnValue: false)
          as bool);

  @override
  _i4.Future<int> get length =>
      (super.noSuchMethod(
            Invocation.getter(#length),
            returnValue: _i4.Future<int>.value(0),
          )
          as _i4.Future<int>);

  @override
  _i4.Future<bool> get isEmpty =>
      (super.noSuchMethod(
            Invocation.getter(#isEmpty),
            returnValue: _i4.Future<bool>.value(false),
          )
          as _i4.Future<bool>);

  @override
  _i4.Future<R> get first =>
      (super.noSuchMethod(
            Invocation.getter(#first),
            returnValue:
                _i7.ifNotNull(
                  _i7.dummyValueOrNull<R>(this, Invocation.getter(#first)),
                  (R v) => _i4.Future<R>.value(v),
                ) ??
                _FakeFuture_3<R>(this, Invocation.getter(#first)),
          )
          as _i4.Future<R>);

  @override
  _i4.Future<R> get last =>
      (super.noSuchMethod(
            Invocation.getter(#last),
            returnValue:
                _i7.ifNotNull(
                  _i7.dummyValueOrNull<R>(this, Invocation.getter(#last)),
                  (R v) => _i4.Future<R>.value(v),
                ) ??
                _FakeFuture_3<R>(this, Invocation.getter(#last)),
          )
          as _i4.Future<R>);

  @override
  _i4.Future<void> cancel() =>
      (super.noSuchMethod(
            Invocation.method(#cancel, []),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Stream<R> asBroadcastStream({
    void Function(_i4.StreamSubscription<R>)? onListen,
    void Function(_i4.StreamSubscription<R>)? onCancel,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#asBroadcastStream, [], {
              #onListen: onListen,
              #onCancel: onCancel,
            }),
            returnValue: _i4.Stream<R>.empty(),
          )
          as _i4.Stream<R>);

  @override
  _i4.StreamSubscription<R> listen(
    void Function(R)? onData, {
    Function? onError,
    void Function()? onDone,
    bool? cancelOnError,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #listen,
              [onData],
              {
                #onError: onError,
                #onDone: onDone,
                #cancelOnError: cancelOnError,
              },
            ),
            returnValue: _FakeStreamSubscription_4<R>(
              this,
              Invocation.method(
                #listen,
                [onData],
                {
                  #onError: onError,
                  #onDone: onDone,
                  #cancelOnError: cancelOnError,
                },
              ),
            ),
          )
          as _i4.StreamSubscription<R>);

  @override
  _i4.Stream<R> where(bool Function(R)? test) =>
      (super.noSuchMethod(
            Invocation.method(#where, [test]),
            returnValue: _i4.Stream<R>.empty(),
          )
          as _i4.Stream<R>);

  @override
  _i4.Stream<S> map<S>(S Function(R)? convert) =>
      (super.noSuchMethod(
            Invocation.method(#map, [convert]),
            returnValue: _i4.Stream<S>.empty(),
          )
          as _i4.Stream<S>);

  @override
  _i4.Stream<E> asyncMap<E>(_i4.FutureOr<E> Function(R)? convert) =>
      (super.noSuchMethod(
            Invocation.method(#asyncMap, [convert]),
            returnValue: _i4.Stream<E>.empty(),
          )
          as _i4.Stream<E>);

  @override
  _i4.Stream<E> asyncExpand<E>(_i4.Stream<E>? Function(R)? convert) =>
      (super.noSuchMethod(
            Invocation.method(#asyncExpand, [convert]),
            returnValue: _i4.Stream<E>.empty(),
          )
          as _i4.Stream<E>);

  @override
  _i4.Stream<R> handleError(
    Function? onError, {
    bool Function(dynamic)? test,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#handleError, [onError], {#test: test}),
            returnValue: _i4.Stream<R>.empty(),
          )
          as _i4.Stream<R>);

  @override
  _i4.Stream<S> expand<S>(Iterable<S> Function(R)? convert) =>
      (super.noSuchMethod(
            Invocation.method(#expand, [convert]),
            returnValue: _i4.Stream<S>.empty(),
          )
          as _i4.Stream<S>);

  @override
  _i4.Future<dynamic> pipe(_i4.StreamConsumer<R>? streamConsumer) =>
      (super.noSuchMethod(
            Invocation.method(#pipe, [streamConsumer]),
            returnValue: _i4.Future<dynamic>.value(),
          )
          as _i4.Future<dynamic>);

  @override
  _i4.Stream<S> transform<S>(_i4.StreamTransformer<R, S>? streamTransformer) =>
      (super.noSuchMethod(
            Invocation.method(#transform, [streamTransformer]),
            returnValue: _i4.Stream<S>.empty(),
          )
          as _i4.Stream<S>);

  @override
  _i4.Future<R> reduce(R Function(R, R)? combine) =>
      (super.noSuchMethod(
            Invocation.method(#reduce, [combine]),
            returnValue:
                _i7.ifNotNull(
                  _i7.dummyValueOrNull<R>(
                    this,
                    Invocation.method(#reduce, [combine]),
                  ),
                  (R v) => _i4.Future<R>.value(v),
                ) ??
                _FakeFuture_3<R>(this, Invocation.method(#reduce, [combine])),
          )
          as _i4.Future<R>);

  @override
  _i4.Future<S> fold<S>(S? initialValue, S Function(S, R)? combine) =>
      (super.noSuchMethod(
            Invocation.method(#fold, [initialValue, combine]),
            returnValue:
                _i7.ifNotNull(
                  _i7.dummyValueOrNull<S>(
                    this,
                    Invocation.method(#fold, [initialValue, combine]),
                  ),
                  (S v) => _i4.Future<S>.value(v),
                ) ??
                _FakeFuture_3<S>(
                  this,
                  Invocation.method(#fold, [initialValue, combine]),
                ),
          )
          as _i4.Future<S>);

  @override
  _i4.Future<String> join([String? separator = '']) =>
      (super.noSuchMethod(
            Invocation.method(#join, [separator]),
            returnValue: _i4.Future<String>.value(
              _i7.dummyValue<String>(
                this,
                Invocation.method(#join, [separator]),
              ),
            ),
          )
          as _i4.Future<String>);

  @override
  _i4.Future<bool> contains(Object? needle) =>
      (super.noSuchMethod(
            Invocation.method(#contains, [needle]),
            returnValue: _i4.Future<bool>.value(false),
          )
          as _i4.Future<bool>);

  @override
  _i4.Future<void> forEach(void Function(R)? action) =>
      (super.noSuchMethod(
            Invocation.method(#forEach, [action]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<bool> every(bool Function(R)? test) =>
      (super.noSuchMethod(
            Invocation.method(#every, [test]),
            returnValue: _i4.Future<bool>.value(false),
          )
          as _i4.Future<bool>);

  @override
  _i4.Future<bool> any(bool Function(R)? test) =>
      (super.noSuchMethod(
            Invocation.method(#any, [test]),
            returnValue: _i4.Future<bool>.value(false),
          )
          as _i4.Future<bool>);

  @override
  _i4.Stream<R1> cast<R1>() =>
      (super.noSuchMethod(
            Invocation.method(#cast, []),
            returnValue: _i4.Stream<R1>.empty(),
          )
          as _i4.Stream<R1>);

  @override
  _i4.Future<List<R>> toList() =>
      (super.noSuchMethod(
            Invocation.method(#toList, []),
            returnValue: _i4.Future<List<R>>.value(<R>[]),
          )
          as _i4.Future<List<R>>);

  @override
  _i4.Future<Set<R>> toSet() =>
      (super.noSuchMethod(
            Invocation.method(#toSet, []),
            returnValue: _i4.Future<Set<R>>.value(<R>{}),
          )
          as _i4.Future<Set<R>>);

  @override
  _i4.Future<E> drain<E>([E? futureValue]) =>
      (super.noSuchMethod(
            Invocation.method(#drain, [futureValue]),
            returnValue:
                _i7.ifNotNull(
                  _i7.dummyValueOrNull<E>(
                    this,
                    Invocation.method(#drain, [futureValue]),
                  ),
                  (E v) => _i4.Future<E>.value(v),
                ) ??
                _FakeFuture_3<E>(
                  this,
                  Invocation.method(#drain, [futureValue]),
                ),
          )
          as _i4.Future<E>);

  @override
  _i4.Stream<R> take(int? count) =>
      (super.noSuchMethod(
            Invocation.method(#take, [count]),
            returnValue: _i4.Stream<R>.empty(),
          )
          as _i4.Stream<R>);

  @override
  _i4.Stream<R> takeWhile(bool Function(R)? test) =>
      (super.noSuchMethod(
            Invocation.method(#takeWhile, [test]),
            returnValue: _i4.Stream<R>.empty(),
          )
          as _i4.Stream<R>);

  @override
  _i4.Stream<R> skip(int? count) =>
      (super.noSuchMethod(
            Invocation.method(#skip, [count]),
            returnValue: _i4.Stream<R>.empty(),
          )
          as _i4.Stream<R>);

  @override
  _i4.Stream<R> skipWhile(bool Function(R)? test) =>
      (super.noSuchMethod(
            Invocation.method(#skipWhile, [test]),
            returnValue: _i4.Stream<R>.empty(),
          )
          as _i4.Stream<R>);

  @override
  _i4.Stream<R> distinct([bool Function(R, R)? equals]) =>
      (super.noSuchMethod(
            Invocation.method(#distinct, [equals]),
            returnValue: _i4.Stream<R>.empty(),
          )
          as _i4.Stream<R>);

  @override
  _i4.Future<R> firstWhere(bool Function(R)? test, {R Function()? orElse}) =>
      (super.noSuchMethod(
            Invocation.method(#firstWhere, [test], {#orElse: orElse}),
            returnValue:
                _i7.ifNotNull(
                  _i7.dummyValueOrNull<R>(
                    this,
                    Invocation.method(#firstWhere, [test], {#orElse: orElse}),
                  ),
                  (R v) => _i4.Future<R>.value(v),
                ) ??
                _FakeFuture_3<R>(
                  this,
                  Invocation.method(#firstWhere, [test], {#orElse: orElse}),
                ),
          )
          as _i4.Future<R>);

  @override
  _i4.Future<R> lastWhere(bool Function(R)? test, {R Function()? orElse}) =>
      (super.noSuchMethod(
            Invocation.method(#lastWhere, [test], {#orElse: orElse}),
            returnValue:
                _i7.ifNotNull(
                  _i7.dummyValueOrNull<R>(
                    this,
                    Invocation.method(#lastWhere, [test], {#orElse: orElse}),
                  ),
                  (R v) => _i4.Future<R>.value(v),
                ) ??
                _FakeFuture_3<R>(
                  this,
                  Invocation.method(#lastWhere, [test], {#orElse: orElse}),
                ),
          )
          as _i4.Future<R>);

  @override
  _i4.Future<R> singleWhere(bool Function(R)? test, {R Function()? orElse}) =>
      (super.noSuchMethod(
            Invocation.method(#singleWhere, [test], {#orElse: orElse}),
            returnValue:
                _i7.ifNotNull(
                  _i7.dummyValueOrNull<R>(
                    this,
                    Invocation.method(#singleWhere, [test], {#orElse: orElse}),
                  ),
                  (R v) => _i4.Future<R>.value(v),
                ) ??
                _FakeFuture_3<R>(
                  this,
                  Invocation.method(#singleWhere, [test], {#orElse: orElse}),
                ),
          )
          as _i4.Future<R>);

  @override
  _i4.Future<R> elementAt(int? index) =>
      (super.noSuchMethod(
            Invocation.method(#elementAt, [index]),
            returnValue:
                _i7.ifNotNull(
                  _i7.dummyValueOrNull<R>(
                    this,
                    Invocation.method(#elementAt, [index]),
                  ),
                  (R v) => _i4.Future<R>.value(v),
                ) ??
                _FakeFuture_3<R>(this, Invocation.method(#elementAt, [index])),
          )
          as _i4.Future<R>);

  @override
  _i4.Stream<R> timeout(
    Duration? timeLimit, {
    void Function(_i4.EventSink<R>)? onTimeout,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#timeout, [timeLimit], {#onTimeout: onTimeout}),
            returnValue: _i4.Stream<R>.empty(),
          )
          as _i4.Stream<R>);
}
