name: invest_agent
description: "A ETF technical analysis Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  collection: ^1.19.0
  archive: ^4.0.7
  equatable: ^2.1.0
  flutter_colorpicker: ^1.1.0
  flutter_secure_storage: ^10.0.0
  file_picker: ^10.3.8
  flutter_math_fork: ^0.7.4
  http: ^1.6.0
  http_parser: ^4.1.2
  intl: ^0.20.2
  dart_duckdb: ^1.4.4
  sealed_currencies: ^3.0.1
  flutter_riverpod: ^3.1.0
  path_provider: ^2.1.5
  riverpod_annotation: ^4.0.0
  url_launcher: ^6.3.2
  grpc: ^5.1.0
  protobuf: ^6.0.0

  cupertino_icons: ^1.0.8
  path: ^1.9.1
  freezed_annotation: ^3.1.0
  json_annotation: ^4.9.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  test: ^1.24.0
  mockito: ^5.2.0
  riverpod_generator: ^4.0.0+1
  build_runner: ^2.13.1
  custom_lint: ^0.8.1
  riverpod_lint: ^3.1.0
  flutter_lints: ^6.0.0
  freezed: ^3.2.3
  json_serializable: ^6.11.2

dependency_overrides:
  vector_math: ^2.2.0

flutter:
  uses-material-design: true
  assets:
    - cache/cache.db
    - cache/analysis.db
