syntax = "proto3";

package trading;

import "google/protobuf/empty.proto";
import "asset.proto";
import "indicators.proto";
import "price.proto";

service InvestAgentService {
  // Two-side communication: stream of requests to stream of results
  rpc CalculateIndicators (stream TradingRequest) returns (stream TradingResponse);
  rpc Assets(stream trading.asset.AssetsRequest) returns (google.protobuf.Empty);
}

// Constraint 1: TradingRequest class definition
message TradingRequest {
  repeated trading.price.IndexPriceItem prices = 1;
  repeated trading.indicators.Indicator indicators = 2;
}


// Constraint 2: Compliable with IndicatorResultMap
// (Map<IndicatorType, List<BaseIndicatorResult>>)
message TradingResponse {
  // Key is the IndicatorType (as a string or integer)
  // We use string key to map easily to IndicatorType.name
  map<string, trading.indicators.IndicatorResultList> results = 1;
}

