import 'package:invest_agent/model/cache_schema.dart';

class PortfolioConfigSchema implements CacheSchema {
  static const String cacheName = "portfolio";
  static const String cacheSequenceName = "portfolio_sequence";
  static const String junctionTable = "portfolio_meta_links";
  static const String cacheJunctionSequenceName = "portfolio_junction_sequence";

  @override
  String get create =>
    '''
    CREATE TABLE IF NOT EXISTS $cacheName (
      id INTEGER PRIMARY KEY DEFAULT nextval('$cacheSequenceName'),
      portfolio_name TEXT NOT NULL,
      target_weight FLOAT NOT NULL,
      rebalance_threshold FLOAT DEFAULT 0.05,
      UNIQUE(portfolio_name)
    );
    -- Junction Table for Multiple Meta IDs
    CREATE TABLE IF NOT EXISTS $junctionTable (
      portfolio_id INTEGER NOT NULL,
      meta_id INTEGER NOT NULL,
      PRIMARY KEY (portfolio_id, meta_id),
      FOREIGN KEY (portfolio_id) REFERENCES $cacheName (id)
    );
    ''';

  @override
  String get createKey =>
    '''
    CREATE SEQUENCE IF NOT EXISTS '$cacheSequenceName' START 1;
    -- Create Junction Table sequence
    CREATE SEQUENCE IF NOT EXISTS '$cacheJunctionSequenceName' START 1; 
  ''';

  @override
  String get deleteAll => "DELETE FROM $cacheName;";

  @override
  String deleteOne(Cache cache) {
    final id = (cache as PortfolioConfig).id;
    return "DELETE FROM $cacheName WHERE id = $id;";
  }

  @override
  String get readAll =>
     '''
      SELECT 
        p.id, 
        p.portfolio_name, 
        p.target_weight, 
        p.rebalance_threshold,
        list(m.meta_id) as meta_ids
      FROM $cacheName p
      LEFT JOIN $junctionTable m ON p.id = m.portfolio_id
      GROUP BY p.id, p.portfolio_name, p.target_weight, p.rebalance_threshold
      ORDER BY p.id DESC; 
     ''';

  @override
  String readOne(Cache cache) {
    final id = (cache as PortfolioConfig).id;
    return '''
      SELECT 
        p.id, p.portfolio_name, p.target_weight, p.rebalance_threshold,
        list(m.meta_id) 
      FROM $cacheName p 
      LEFT JOIN $junctionTable m ON p.id = m.portfolio_id 
      WHERE p.id = $id
      GROUP BY p.id, p.portfolio_name, p.target_weight, p.rebalance_threshold;
    ''';
  }

  @override
  String saveOne(Cache cache) {
    final portfolioConfig = cache as PortfolioConfig;
    final portfolioName = portfolioConfig.portfolioName;
    final targetWeight = portfolioConfig.targetWeight;
    final rebalanceThreshold = portfolioConfig.rebalanceThreshold;
    final metaIds = portfolioConfig.metaIds;

    // We use DuckDB's unnest() to insert multiple meta_ids in one block
    // currval() gets the ID generated by the first statement
    final idsArray = "[${metaIds.join(',')}]";
    return '''
     INSERT INTO $cacheName (portfolio_name, target_weight, rebalance_threshold)
      VALUES ('$portfolioName', $targetWeight, $rebalanceThreshold);
      
      INSERT INTO $junctionTable (portfolio_id, meta_id)
      SELECT currval('$cacheSequenceName'), unnest($idsArray);
     ''';
  }

  @override
  String updateOne(Cache cache) {
    final portfolioConfig = cache as PortfolioConfig;
    final id = portfolioConfig.id;
    final portfolioName = portfolioConfig.portfolioName;
    final targetWeight = portfolioConfig.targetWeight;
    final rebalanceThreshold = portfolioConfig.rebalanceThreshold;
    final metaIds = portfolioConfig.metaIds;

    final idsArray = "[${metaIds.join(',')}]";

    return '''
     UPDATE $cacheName
      SET portfolio_name = '$portfolioName',
          target_weight = $targetWeight,
          rebalance_threshold = $rebalanceThreshold
      WHERE id = $id;

      DELETE FROM $junctionTable WHERE portfolio_id = $id;

      INSERT INTO $junctionTable (portfolio_id, meta_id)
      SELECT $id, unnest($idsArray);
      ''';
  }
}

class PortfolioConfig implements Cache{
  final int? id;
  final String portfolioName;
  final List<int> metaIds;
  final double targetWeight;
  final double rebalanceThreshold;

  PortfolioConfig({
  this.id,
  this.portfolioName = "",
  required this.metaIds,
  this.targetWeight = 0.25,
  this.rebalanceThreshold = 0.05,
  });

  @override
  factory PortfolioConfig.from(List<Object?> row) {
    if (row.isEmpty && row.length < 5) {
      throw Exception("Invalidate input data");
    }
    return PortfolioConfig(
      id: row[0] as int?,
      portfolioName: row[1] as String,
      metaIds: [],  // Populate separate metaIds from junction source
      targetWeight: (row[3] as num).toDouble(),
      rebalanceThreshold: (row[4] as num).toDouble(),
    );
  }

  @override
  Map<String, dynamic> toMap() => {
  'portfolio_name': portfolioName,
  'target_weight': targetWeight,
  'rebalance_threshold': rebalanceThreshold,
  };
}